from rest_framework import viewsets
from .models import Income
from .serializers import IncomeSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import action

class IncomeViewSet( viewsets.ModelViewSet ):
    """
    REST API for managing incomes.

    Actions generated by ModelViewSet:
    - GET /api/incomes/ or /incomes/ lists incomes.
    - GET /api/incomes/{id}/ or /incomes/{id}/ retrieves an income by id.
    - POST /api/incomes/ or /incomes/ creates an income.
    - PUT/PATCH /api/incomes/{id}/ or /incomes/{id}/ updates an income by id.
    - DELETE /api/incomes/{id}/ or /incomes/{id}/ deletes an income by id.

    Custom actions:
    - PUT /api/incomes/update-by-user-account/
    - DELETE /api/incomes/delete-by-user-account/
    """
    queryset = Income.objects.all()
    serializer_class = IncomeSerializer

    def  get_queryset(self):
        """
        Allows the income list to be filtered by user and/or accounting account.

        Supported query params:
        - user_id: id of the user who owns the income.
        - account_id: id of the accounting account linked to the income.
        """
        queryset = Income.objects.all()

        userId = self.request.query_params.get('user_id')
        accountId =  self.request.query_params.get('account_id')

        if userId:
            queryset = queryset.filter(user_id=userId)

        if accountId:
            queryset = queryset.filter(accounting_account_id=accountId)

        print( queryset )

        return queryset

    def list(self, request, *args, **kwargs):
        """Lists incomes and returns an empty list when the filters have no results."""
        queryset = self.get_queryset()

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['put'], url_path='update-by-user-account')
    def update_by_user_account(self, request):
        """
        Updates an income using user_id and account_id from the request body.

        Example body:
        {
            "user_id": 1,
            "account_id": 2,
            "value": "150000.00",
            "date": "2026-06-14T10:00:00Z"
        }
        """
        user_id = request.data.get('user_id')
        account_id = request.data.get('account_id')

        try:
            income = Income.objects.get(
                user_id=user_id,
                accounting_account_id=account_id
            )
        except Income.DoesNotExist:
            return Response({"error": "No encontrado"}, status=404)

        serializer = self.get_serializer(income, data=request.data)

        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        serializer.save()

        return Response(serializer.data)


    def create(self, request, *args, **kwargs):
        """Creates an income by validating the fields defined in IncomeSerializer."""
        print( "REQUEST DATA:", request.data )
        serializer = self.get_serializer(data=request.data)

        if not serializer.is_valid():
            print( "SERIALIZER ERRORS:", serializer.errors )
            return Response(serializer.errors, status=400)

        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    @action(detail=False, methods=['delete'], url_path='delete-by-user-account')
    def delete_by_user_account(self, request):
        """
        Deletes an income using user_id and account_id as query params.

        Example:
        DELETE /api/incomes/delete-by-user-account/?user_id=1&account_id=2
        """
        user_id = request.query_params.get('user_id')
        account_id = request.query_params.get('account_id')

        try:
            income = Income.objects.get(
                user_id=user_id,
                accounting_account_id=account_id
            )
        except Income.DoesNotExist:
            return Response({"error": "No encontrado"}, status=404)

        income.delete()
        return Response(status=204)
